name: Android build

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: ["android"]
  pull_request:
    branches: ["android"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build Cemu for Android
        run: |
          cd ./src/android
          ./gradlew assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cemu-android
          path: |
            ./src/android/app/build/outputs/apk/*/*.apk
            ./src/android/app/build/outputs/apk/*/*.aab
